# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsne_la <- function(G0, S0, N0, LA1, BETA) {
    .Call('meteR_gsne_la', PACKAGE = 'meteR', G0, S0, N0, LA1, BETA)
}

gsne_Z <- function(LA1, LA2, LA3, S0, N0) {
    .Call('meteR_gsne_Z', PACKAGE = 'meteR', LA1, LA2, LA3, S0, N0)
}

timesTwo <- function(x) {
    .Call('meteR_timesTwo', PACKAGE = 'meteR', x)
}

